name: Testing configuration variables

on:
  workflow_dispatch

env:
  cloud: Microsoft Azure

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello to Anup"
        run: echo "$Greeting $First-name is using $cloud for ${{ vars.project_name}}
        env:
          First_name: Anup
