name: Testing configuration variables

on:
  workflow_dispatch

env:
  cloud: google-cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello to Vishal"
        run: echo "${Greeting} ${first_name} is
