name: Testing workflow variables

on:
  workflow_dispatch

env:
  cloud: Microsoft Azure

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Hona it's Monday"
        run: echo "$Greeting $First_Name is using $cloud"
        env:
          First_Name: Anup
